### ISSUE TITLE
Please delete thanks

### ISSUE THREAD

**Issue by HistoricallyCorrect** [leonardochaia/dotnet-affected#111]
I solved it. Please delete this issue. Thanks.

**Comment by leonardochaia** [comment]
Hi @HistoricallyCorrect , it would be historically correct to leave the issue here so we can help others in the future :smile: 

Happy to help if you have further questions :+1:  or if you wanna get an opinion on the solution you've come up with.

Regards,
Leo.

**Comment by HistoricallyCorrect** [comment]
Thanks for the reply. I guess I'll resurrect this issue once I got the workflow worked out (in principle).

**Comment by leonardochaia** [comment]
Sure thing. Feel free to create a discussion to review / analyze strategies. Happy to help.

Leo.
