### ISSUE TITLE
Support other kinds of MSBuild projects

### ISSUE THREAD

**Issue by leonardochaia** [leonardochaia/dotnet-affected#16]
Currently, when using `--repository-path`, only `.csproj` files will be discovered.

When using a `--solution-path`, all projects inside the solution will be taken into account.

We should discover all MSBuild projs when using the `--repository-path` as well.

**Comment by cmeeren** [comment]
Does this mean it does not pick up `.fsproj` or `.vbproj`? Would be great to have those!

**Comment by leonardochaia** [comment]
Hi @cmeeren, correct, `.fsproj` / `.vbproj` are only being discovered when using a solution.

Apparently, we just need to tweak the project discovery:

https://github.com/leonardochaia/dotnet-affected/blob/9b9aa618d76b8c6912ba42198109b9a7862a634d/src/DotnetAffected.Core/ProjectDiscovery/DirectoryProjectDiscoverer.cs#L10
