### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by wterpstra** [leonardochaia/dotnet-affected#19]
The dotnet-affected tool cannot run on .NET 6.

```
You can invoke the tool using the following command: dotnet-affected
Tool 'dotnet-affected' (version '2.0.0-preview-1') was successfully installed.
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=ubuntu.20.04-x64
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

**Comment by wterpstra** [comment]
Having some CI troubles. It looks like the script is sucessfully installing the .NET 6 SDK:
https://github.com/leonardochaia/dotnet-affected/runs/4166725509?check_suite_focus=true#step:3:23

However, the dotnet restore step does not seem to find the SDK:
https://github.com/leonardochaia/dotnet-affected/runs/4166725509?check_suite_focus=true#step:4:19

**Comment by omer-za** [comment]
Simply use https://github.com/actions/setup-dotnet for installation dotnet. it should work.

**Comment by leonardochaia** [comment]
Hi @omer-za .
This project has a script to install the proper versions required when developing. We use that as well in CI so that we don't have any differences between CI and local development.

That being said, this should be fixed by now, but I'm not sure if a new release has been issued.

For tracking purposes see https://github.com/microsoft/MSBuildSdks/issues/309 and https://github.com/NuGet/Home/issues/11376
