### ISSUE TITLE
.NET Core 3.1 support

### ISSUE THREAD

**Issue by wterpstra** [leonardochaia/dotnet-affected#2]
First of all, thanks for putting all this effort into this tool!

I was wondering if it's possible to support .NET Core 3.1 as well. I tested this locally and had some issues at first with the earlier SDK versions (3.1.100, 3.1.301) not resolving the type `GraphConstructionMetrics` correctly. However with latest SDK version 4.1.408 it is working fine.

I will take the liberty to open a pull request for this!

**Comment by leonardochaia** [comment]
Hey @wterpstra! I'm glad someone else is giving this a try.

I'll take a look during the weekend to the issues and PRs you have created, thank you!!

Regards,
Leo.
