### ISSUE TITLE
Support reading projects from a solution file

### ISSUE THREAD

**Issue by wterpstra** [leonardochaia/dotnet-affected#4]
I have a repository with a large amount of projects inside that i'd like to scan for affected changes. This repo contains a sub repo with also many projects, however, my project only uses a single project from that subrepo (not optimal, but it works). This project is included in my solution but the others are not. 

I have tested something where I added the functionality to pass a `--solution-path <solution-path>` argument with the path to the solution from which to load the projects. I will take the liberty to create a pull request so you can inspect this feature.

**Comment by wterpstra** [comment]
Hey @leonardochaia what do you think about this?

**Comment by leonardochaia** [comment]
Hey there. I'm sorry I'm not spending time on this project :( I am kinda caught in work.

I've left some comments in the PR, but yeah let's merge it.
