### ISSUE TITLE
Add support for package version override in detecting changes in NuGet versions

### ISSUE THREAD

**Issue by wterpstra** [leonardochaia/dotnet-affected#40]
Minor issue, it might mark projects as affected when they are not necessarily.

NuGet 6.2 introduces central package management and drops the preview flag. However they also support overriding individual packages on individual projects. When overridden we should not mark those projects affected when the centrally managed version changes.

https://devblogs.microsoft.com/nuget/introducing-central-package-management/

**Comment by leonardochaia** [comment]
Hi @wterpstra ! Nice to see it out of preview.

Do you wanna give this a go?

**Comment by leonardochaia** [comment]
To add on to this:

> What this means is that if you had multiple Directory.Packages.props files in your repository, the file that is closest to your project’s directory will be evaluated for it. This allows you extra control at various levels of your repository.

There are properties in the MSBuild Projects that tells us the location of the `Directory.Package.props` file being used.
We need to refactor and use that to determine which file to consider for each project.
