### ISSUE TITLE
Finding affected projects take longer then expected

### ISSUE THREAD

**Issue by omer-za** [leonardochaia/dotnet-affected#64]
Hi, I have cases when finding affected projects takes more then 10 minutes, then I abort my job and can't continue from this point.
I suggest to have an option to configure timeout and if timeout reached then mark all solution as affected (all csproj files).

We have a big solution project and sometimes when there's a lot of changes and it just hangs forever :(

**Comment by leonardochaia** [comment]
Hi @omer-za 
What version of dotnet-affected and dotnet SDK are you using?

Have you tried dotnet-affected [v3-preview-3](https://www.nuget.org/packages/dotnet-affected/3.0.0-preview-3)?
Several improvements where made on how affected project detection works.

I haven't run the benchmarks in a while but the [MacroBenchmark](https://github.com/leonardochaia/dotnet-affected/blob/main/benchmarks/dotnet-affected.Benchmarks/MacroBenchmarks.cs#L24), which I don't know how much we can trust it's results, [benchmarked 1k projects in ~5.6s](https://github.com/leonardochaia/dotnet-affected/pull/50#issue-1315667169)

It would be very nice to improve performance, so perhaps the benchmarks are not good enough or there's something different with your solution.

**Comment by omer-za** [comment]
We use dotnet sdk 6.0.404 and version 2.2.0 of the tool.
It doesn't happen much when it hangs, only when a lot of files changes in our solution which contains around 300 projects
