### ISSUE TITLE
Version 3.1.0 does not work on Alpine Linux

### ISSUE THREAD

**Issue by bartlomiejgawel** [leonardochaia/dotnet-affected#75]
Hello,

I've noticed a regression introduced with version 3.1.0.

You can reproduce it in the following way:
1. Clone https://github.com/bartlomiejgawel/dotnet-affected-bug
2. Create a docker image and install version `3.0.0` by running the following command:
```bash
docker build -f Dockerfile -t dotnet-affected-3.0.0-alpine .
```
for the following `Dockerfile` file:
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine

RUN dotnet tool install dotnet-affected --global --version 3.0.0

ENV PATH "$PATH:/root/.dotnet/tools"
```
3. Create a docker image and install version `3.1.0` by running the following command:
```bash
docker build -f Dockerfile -t dotnet-affected-3.1.0-alpine .
```
for the following `Dockerfile` file:
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine

RUN dotnet tool install dotnet-affected --global --version 3.1.0

ENV PATH "$PATH:/root/.dotnet/tools"
```
4. Run the following command:
```bash
docker run --rm -v "$(pwd):/src" -w /src dotnet-affected-3.0.0-alpine /bin/sh -c "dotnet affected --from b4d7eab --to 71b0a49"
```
You can see that it works smoothly and creates an `affected.proj` file as expected.

5. Run the following command:
```bash
docker run --rm -v "$(pwd):/src" -w /src dotnet-affected-3.1.0-alpine /bin/sh -c "dotnet affected --from b4d7eab --to 71b0a49"
```
You can see that it exits with status code `139`.

Notice that standard dotnet SDK works correctly (also outside the container on Windows):
1. Create a docker image and install version `3.1.0` by running the following command:
```bash
docker build -f Dockerfile -t dotnet-affected-3.1.0 .
```
for the following `Dockerfile` file:
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0

RUN dotnet tool install dotnet-affected --global --version 3.1.0

ENV PATH "$PATH:/root/.dotnet/tools"
```
2. Run the following command:
```bash
docker run --rm -v "$(pwd):/src" -w /src dotnet-affected-3.1.0 /bin/sh -c "dotnet affected --from b4d7eab --to 71b0a49"
```
You can see that it works smoothly and creates an `affected.proj` file as expected.

I've checked what's changed between `3.0.0` and `3.1.0`:
https://github.com/leonardochaia/dotnet-affected/compare/v3.0.0...v3.1.0

And maybe one of the updated packages caused this regression?

**Comment by leonardochaia** [comment]
Hi @bartlomiejgawel , I have narrowed this down to `Microsoft.Build.Locator`. 
Downgrading to `Microsoft.Build.Locator`  v1.4.1 solves the issue.
I'll release dotnet-affected v3.1.1 with the fix.
