### ISSUE TITLE
Add format options to README.md and --help

### ISSUE THREAD

**Issue by xIceFox** [leonardochaia/dotnet-affected#77]
First of all, I love your project! Thank you for your work!

It would be cool to have a support for a command flag, which outputs a txt/json (preferably json) besides the traversal file, including all the affected project names (could be a file or just command line output). This would be especially useful for ci runs where you need to decide which projects to deploy. With json, you could pipe the information to further tools and parse them to objects.

I would really appreciate if this would be included in this tool.

**Comment by leonardochaia** [comment]
Hi @xIceFox, I'm glad you are finding the tool useful.

[Documentation](https://github.com/leonardochaia/dotnet-affected#multiple-output-formats) can be improved but we do have text and json output. We call them Output Formatters, and currently on v3.1 there's `traversal`, `text` and `json`

For example, using `--format text traversal json` outputs `affected.proj`, `affected.txt` and `affected.json`.
Do note that the `json` Output Formatter is available on dotnet-affected v.3.1.

Let me know if this helps.

Kind regards,
Leo.

**Comment by xIceFox** [comment]
Hello @leonardochaia Thank you for the fast respond! 

That is exactly what I was looking for! 
I just tested it locally, works like a charm.

Like you wrote, in the documentation it is not totally clear what options the "--format" flag has. Maybe this issue could be an improvement for that.

To help you a little bit, i will write down these things and create a pull request.

**Comment by leonardochaia** [comment]
Hi @xIceFox , glad to know it is working.

> To help you a little bit, i will write down these things and create a pull request.

That would be really appreciated thanks :+1:

**Comment by xIceFox** [comment]
@leonardochaia I opened #78.
