### ISSUE TITLE
Ability to exclude projects

### ISSUE THREAD

**Issue by JoaoEdu93** [leonardochaia/dotnet-affected#80]
We have unit tests and integration tests in the same repository.
We have a CI pipeline where the unit tests will run and we don't want this pipeline to run the integration tests, even if some of these projects have had changes.
So I think it would be useful to have some way to exclude these projects from the dotnet-affected output.

**Comment by leonardochaia** [comment]
Hi @JoaoEdu93. 
For the CLI, this should get fixed with #79 

In the meantime, take a look at [my comments here](https://github.com/leonardochaia/dotnet-affected/pull/79#issuecomment-1469912338)
